### ISSUE TITLE
Android 10 - deprecated method to store cropped picture

### ISSUE THREAD

**Issue by yairopro** [Radweb/react-native-crop-image#4]
https://github.com/Radweb/react-native-crop-image/blob/91fedf62766b6b2c33f5a76a35be95b1e5bda918/android/src/main/java/com/radweb/cropimage/RNCropImageModule.java#L70

[`getExternalStoragePublicDirectory` is deprecated.](https://developer.android.com/reference/android/os/Environment#getExternalStoragePublicDirectory(java.lang.String))

The simplest solution would be to store the image in the app folder. It's straight forward and no permission is needed.
Should I start a PR implementing this ?

----
For those passing by, here's a **workaround** for Android 10 (won't work on Android 11):
Add this attribute in you app tag in your manifest:
```xml
<application
	// ...
	android:requestLegacyExternalStorage="true">
```

**Comment by yairopro** [comment]
@iWader

**Comment by iWader** [comment]
This repo isn't maintained. Please fork and maintain your own version 👍
